{"name": "Mouse Over", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /Users/ivanvoronov/.cache/selenium/chromedriver/mac-arm64/131.0.6778.204/chromedriver unexpectedly exited. Status code was: 1", "trace": "request = <SubRequest 'driver' for <Function test_mouse_page[firefox]>>\n\n    @pytest.fixture(scope=\"function\", autouse=True, params=[\"chrome\", \"firefox\"])\n    def driver(request):\n        browser = request.param\n        if browser == \"chrome\":\n            options = Options()\n            options.add_argument(\"--no-sandbox\")\n            options.add_argument(\"--disable-dev-shm-usage\")\n            options.add_argument(\"--window-size=1920x1080\")\n            driver = webdriver.Chrome(options=options)\n        elif browser == \"firefox\":\n            options = Options()\n            options.add_argument(\"--headless\")\n            options.add_argument(\"--no-sandbox\")\n            options.add_argument(\"--disable-dev-shm-usage\")\n            options.add_argument(\"--window-size=1920x1080\")\n>           driver = webdriver.Firefox(options=options)\n\nconftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n.venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py:62: in __init__\n    self.service.start()\n.venv/lib/python3.10/site-packages/selenium/webdriver/common/service.py:108: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.firefox.service.Service object at 0x104ba72e0>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service /Users/ivanvoronov/.cache/selenium/chromedriver/mac-arm64/131.0.6778.204/chromedriver unexpectedly exited. Status code was: 1\n\n.venv/lib/python3.10/site-packages/selenium/webdriver/common/service.py:121: WebDriverException"}, "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1735399602615, "stop": 1735399602615, "uuid": "bbc6c591-7cc8-4e43-9640-071fb80972e3", "testCaseId": "320b5f49031d79cda8e69ae88544cdc9", "fullName": "tests.test_features_ui_playground.TestFeaturesUiPlayground#test_mouse_page"}